services:
  match:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./src/.env
    volumes:
      - ./src:/app/src
    depends_on:
      - match_db
  match_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - match_db_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: matchDB


volumes:
  match_db_data:
  